<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "guide"
 *
 * Auto generated by Extension Builder 2014-09-23
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Guide',
	'description' => 'Guides new users through the system.',
	'category' => 'plugin',
	'author' => 'TYPO3 CMS Team',
	'author_email' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.0-6.3.99',
			'yaml_parser' => '1.0.1'
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);